version: '2.1'

services:
  kong-database:
    image: postgres:9.4
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong_password
      POSTGRES_DB: kong
    volumes:
      - ./pgdata:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 30s
      interval: 30s
      retries: 3

  kong-data-migration:
    image: kong:0.11
    links:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USERNAME: kong
      KONG_PG_PASSWORD: kong_password
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    command: kong migrations up --vv
    depends_on:
      kong-database:
        condition: service_healthy

  kong:
    image: kong:0.11
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USERNAME: kong
      KONG_PG_PASSWORD: kong_password
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    restart: on-failure
    links:
      - kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      kong-database:
        condition: service_healthy
      kong-data-migration:
        condition: service_started

  kong-konga-dashboard:
    image: pantsel/konga
    environment:
      NODE_ENV: development
    links:
      - kong
    ports:
      - 1337:1337

  test-api:
    build:
      context: test-api
    command: python app.py
    ports:
      - 8081:8080
